### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by joel-Amaral** [frontend-ao/eventos#1]

**Comment by guibranco** [comment]
@joel-Amaral você pretendia informar sobre algum evento sobre front-end em Angola? Ou criou este issue por engano?

**Comment by joel-Amaral** [comment]
> @joel-Amaral você pretendia informar sobre algum evento sobre front-end em Angola? Ou criou este issue por engano?

Foi por engano

**Comment by joel-Amaral** [comment]
Foi por engano

**Comment by guibranco** [comment]
Ah entendi, vou encerrar ele então!
